AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Kaiju Academy Backend API SAM Template for deploying Node.js Lambda
  functions

  '
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs18.x
    Architectures:
    - x86_64
    Environment:
      Variables:
        LOG_LEVEL: info
Resources:
  KaijuAcademyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,Authorization'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: KaijuAcademyApi
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://kaiju-academy-backend-sam/abeb5e011d8152cf24a543f4d447469f
      Handler: src/index.handler
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /auth/login
            Method: post
        Register:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /auth/register
            Method: post
        ListCourses:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /courses
            Method: get
        GetCourse:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /courses/{id}
            Method: get
        CreateCourse:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /courses
            Method: post
        UpdateCourse:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /courses/{id}
            Method: put
        DeleteCourse:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /courses/{id}
            Method: delete
        ExecuteCode:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /code/execute
            Method: post
        EvaluateCode:
          Type: Api
          Properties:
            RestApiId:
              Ref: KaijuAcademyApi
            Path: /code/evaluate
            Method: post
    Metadata:
      SamResourceId: MainFunction
Outputs:
  MainFunction:
    Description: Main Lambda Function ARN
    Value:
      Fn::GetAtt:
      - MainFunction
      - Arn
  ApiURL:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${KaijuAcademyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/
