AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Kaiju Academy Backend API
  SAM Template for deploying Node.js Lambda functions

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: info
        # JWT Configuration
        JWT_SECRET: '{{resolve:secretsmanager:/kaiju/jwt/secret:SecretString}}'
        USERS_TABLE: kaiju-users
        COURSES_TABLE: kaiju-courses
        COURSE_CONTENT_TABLE: kaiju-course-content

Resources:
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kaiju-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kaiju-courses
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: educator
          AttributeType: S
        - AttributeName: is_published
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EducatorIndex
          KeySchema:
            - AttributeName: educator
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: PublishedIndex
          KeySchema:
            - AttributeName: is_published
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CourseContentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: kaiju-course-content
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: course_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CourseIndex
          KeySchema:
            - AttributeName: course_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # API Gateway
  KaijuAcademyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Main Lambda Function with all routes
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/index.handler
      Policies:
        # DynamoDB CRUD policies
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CourseContentTable
        # Secrets Manager policy for JWT
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/kaiju/jwt/secret-*'
      Events:
        # Auth routes
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /auth/login
            Method: post
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /auth/register
            Method: post
        ValidateToken:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /auth/validate
            Method: get
        UpdateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /auth/profile
            Method: put
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /auth/user
            Method: get
        GetUserById:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /auth/user/{id}
            Method: get
        
        # Course routes
        ListCourses:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses
            Method: get
        GetCourse:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/{id}
            Method: get
        GetFeaturedCourse:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/featured
            Method: get
        CreateCourse:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses
            Method: post
        UpdateCourse:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/{id}
            Method: put
        DeleteCourse:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/{id}
            Method: delete
        
        # Course Content routes
        GetCourseContent:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/{id}/content
            Method: get
        AddCourseContent:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/{id}/content
            Method: post
        UpdateCourseContent:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/content/{id}
            Method: put
        DeleteCourseContent:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /courses/content/{id}
            Method: delete
        
        # Code execution routes
        ExecuteCode:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /code/execute
            Method: post
        EvaluateCode:
          Type: Api
          Properties:
            RestApiId: !Ref KaijuAcademyApi
            Path: /code/evaluate
            Method: post

Outputs:
  MainFunction:
    Description: "Main Lambda Function ARN"
    Value: !GetAtt MainFunction.Arn
  ApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${KaijuAcademyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/" 